/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import org.w3c.dom.ls.LSOutput;

import static org.junit.Assert.*;

public class AppTest {
   sout

    }
}
